### ISSUE TITLE
AudioGuide issues with soundfiles folder on external drive

### ISSUE THREAD

**Issue by steinmetzer** [benhackbarth/audioguide#10]
I have some issues while trying to use a folder with soundfiles on an external SSD drive as corpus.

Here is what I’m doing:
CORPUS = [
csf('/Volumes/T7/other/SoundsAndLoops/Orchidea/_OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/', wholeFile=True)
]

where T7 is my external drive's name.

This is what I get in the terminal after running the scripts

fauvel@Robys-Air ~ % python3 /Users/fauvel/Music/AudioGuide/agConcatenate.py /Users/fauvel/Music/AudioGuide/rs/1st.py
audioguide1.74 -> /Users/fauvel/Music/AudioGuide/audioguide
python3.9.10 -> /opt/homebrew/opt/python@3.9/bin/python3.9
               Evaluating TARGET cage.aiff from 0.00-11.40                
100% [================================================================]
	Found 21 segments (threshold=-25.0 offsetrise=1.50 offsetthreshadd=12.00).

                           Evaluating CORPUS...                           
  0% [----------------------------------------------------------------]
	ings/Harp/ordinario/._Hp-ord-B0-mf-N-N.wav@0.00-100.00                    Traceback (most recent call last):
  File "/Users/fauvel/Music/AudioGuide/agConcatenate.py", line 29, in <module>
    ag.execute()
  File "/Users/fauvel/Music/AudioGuide/audioguide/__init__.py", line 59, in execute
    self.load_corpus()
  File "/Users/fauvel/Music/AudioGuide/audioguide/__init__.py", line 138, in load_corpus
    self.cps = concatenativeclasses.corpus(self.ops.CORPUS, self.ops.CORPUS_GLOBAL_ATTRIBUTES, self.ops.RESTRICT_CORPUS_SELECT_PERCENTAGE_BY_STRING, self.ops.SEARCH_PATHS, self.AnalInterface, self.p)
  File "/Users/fauvel/Music/AudioGuide/audioguide/concatenativeclasses.py", line 522, in __init__
    cpsSeg = sfsegment.corpusSegment(*corpusSegParams)
  File "/Users/fauvel/Music/AudioGuide/audioguide/sfsegment.py", line 141, in __init__
    sfsegment.__init__(self, filename, startSec, endSec, AnalInterface, envDb=envDb, envAttackSec=envAttackSec, envDecaySec=envDecaySec, envSlope=envSlope, normtag='cps')
  File "/Users/fauvel/Music/AudioGuide/audioguide/sfsegment.py", line 24, in __init__
    self.soundfileTotalDuration, self.soundfileChns = AnalInterface.validateAnalResource(self.filename)
  File "/Users/fauvel/Music/AudioGuide/audioguide/anallinkage.py", line 308, in validateAnalResource
    self.initAnalResource(sffile)
  File "/Users/fauvel/Music/AudioGuide/audioguide/anallinkage.py", line 355, in initAnalResource
    self.rawData[sffile]['info'], self.rawData[sffile]['ircamd'] = self.__createDescriptorsFile__(sffile, self.analdir, descriptorfile, infofile, self.ircamdescriptor_bin, self.config_loc)
  File "/Users/fauvel/Music/AudioGuide/audioguide/anallinkage.py", line 288, in __createDescriptorsFile__
    infodict['lengthsec'] = infodict['lengthsamples']/float(infodict['sr'])
KeyError: ‘lengthsamples'

However if I copy the folder on my internal drive I works as expected, so I wondered if there was a bug of some kind accessing a soundfiles folder on an external drive.
Or maybe I just have to address the external folder differently.
I tried with an alias buit no luck either.

**Comment by benhackbarth** [comment]
Thanks Roby. I can confirm that the following options file works on my machine using samples on an external volume: 

TARGET = tsf('cage.aiff', thresh=-25, offsetRise=1.5)
CORPUS = [
csf('/Volumes/data/sample-library/Vienna/10 Harp/Einzelnoten/HA_ES/HA_ES_p', wholeFile=True),
]
SEARCH = [spass('closest_percent', d('effDur-seg', norm=1), d('power-seg', norm=1), percent=25),
spass('closest', d('mfccs'))]
SUPERIMPOSE = si(maxSegment=6)


Can you try running "ls /Volumes/T7/other/SoundsAndLoops/Orchidea/_OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/" in the terminal to see if the files display OK?

**Comment by steinmetzer** [comment]
Yes, everything is listed:

***@***.*** ordinario % ls /Volumes/T7/other/SoundsAndLoops/Orchidea/_OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/
Hp-ord-A#1-ff-N-N.wav		Hp-ord-C#3-ff-N-N.wav		Hp-ord-D2-mf-N-N.wav		Hp-ord-F1-pp-N-N.wav
Hp-ord-A#1-mf-N-N.wav		Hp-ord-C#3-mf-N-N.wav		Hp-ord-D2-pp-N-N.wav		Hp-ord-F2-ff-N-N.wav
Hp-ord-A#1-pp-N-N.wav		Hp-ord-C#3-pp-N-N.wav		Hp-ord-D3-ff-N-N.wav		Hp-ord-F2-mf-N-N.wav
Hp-ord-A#2-ff-N-N.wav		Hp-ord-C#4-ff-N-N.wav		Hp-ord-D3-mf-N-N.wav		Hp-ord-F2-pp-N-N.wav
Hp-ord-A#2-mf-N-N.wav		Hp-ord-C#4-mf-N-N.wav		Hp-ord-D3-pp-N-N.wav		Hp-ord-F3-ff-N-N.wav
Hp-ord-A#2-pp-N-N.wav		Hp-ord-C#4-pp-N-N.wav		Hp-ord-D4-ff-N-N.wav		Hp-ord-F3-mf-N-N.wav
Hp-ord-A#3-ff-N-N.wav		Hp-ord-C#5-ff-N-T15d.wav	Hp-ord-D4-mf-N-N.wav		Hp-ord-F3-pp-N-N.wav
Hp-ord-A#3-mf-N-N.wav		Hp-ord-C#5-mf-N-N.wav		Hp-ord-D4-pp-N-N.wav		Hp-ord-F4-ff-N-N.wav
Hp-ord-A#3-pp-N-N.wav		Hp-ord-C#5-pp-N-N.wav		Hp-ord-D5-ff-N-N.wav		Hp-ord-F4-mf-N-N.wav
Hp-ord-A#4-ff-N-N.wav		Hp-ord-C#6-ff-N-N.wav		Hp-ord-D5-mf-N-N.wav		Hp-ord-F4-pp-N-N.wav
Hp-ord-A#4-mf-N-N.wav		Hp-ord-C#6-mf-N-N.wav		Hp-ord-D5-pp-N-N.wav		Hp-ord-F5-ff-N-N.wav
Hp-ord-A#4-pp-N-N.wav		Hp-ord-C#6-pp-N-N.wav		Hp-ord-D6-ff-N-N.wav		Hp-ord-F5-mf-N-N.wav
Hp-ord-A#5-ff-N-N.wav		Hp-ord-C#7-ff-N-N.wav		Hp-ord-D6-mf-N-N.wav		Hp-ord-F5-pp-N-N.wav
Hp-ord-A#5-mf-N-N.wav		Hp-ord-C#7-mf-N-N.wav		Hp-ord-D6-pp-N-N.wav		Hp-ord-F6-ff-N-N.wav
Hp-ord-A#5-pp-N-N.wav		Hp-ord-C#7-pp-N-N.wav		Hp-ord-D7-ff-N-N.wav		Hp-ord-F6-mf-N-N.wav
Hp-ord-A#6-ff-N-N.wav		Hp-ord-C1-ff-N-N.wav		Hp-ord-D7-mf-N-N.wav		Hp-ord-F6-pp-N-N.wav
Hp-ord-A#6-mf-N-N.wav		Hp-ord-C1-mf-N-N.wav		Hp-ord-D7-pp-N-T15d.wav		Hp-ord-F7-ff-N-N.wav
Hp-ord-A#6-pp-N-N.wav		Hp-ord-C1-pp-N-T17u.wav		Hp-ord-E1-ff-N-N.wav		Hp-ord-F7-mf-N-T13d.wav
Hp-ord-A1-ff-N-N.wav		Hp-ord-C2-ff-N-N.wav		Hp-ord-E1-mf-N-N.wav		Hp-ord-F7-pp-N-N.wav
Hp-ord-A1-mf-N-N.wav		Hp-ord-C2-mf-N-N.wav		Hp-ord-E1-pp-N-N.wav		Hp-ord-G#1-ff-N-N.wav
Hp-ord-A1-pp-N-N.wav		Hp-ord-C2-pp-N-N.wav		Hp-ord-E2-ff-N-N.wav		Hp-ord-G#1-mf-N-N.wav
Hp-ord-A2-ff-N-N.wav		Hp-ord-C3-ff-N-N.wav		Hp-ord-E2-mf-N-N.wav		Hp-ord-G#1-pp-N-T10u.wav
Hp-ord-A2-mf-N-N.wav		Hp-ord-C3-mf-N-N.wav		Hp-ord-E2-pp-N-N.wav		Hp-ord-G#2-ff-N-N.wav
Hp-ord-A2-pp-N-N.wav		Hp-ord-C3-pp-N-N.wav		Hp-ord-E3-ff-N-N.wav		Hp-ord-G#2-mf-N-N.wav
Hp-ord-A3-ff-N-N.wav		Hp-ord-C4-ff-N-N.wav		Hp-ord-E3-mf-N-N.wav		Hp-ord-G#2-pp-N-N.wav
Hp-ord-A3-mf-N-N.wav		Hp-ord-C4-mf-N-N.wav		Hp-ord-E3-pp-N-N.wav		Hp-ord-G#3-ff-N-N.wav
Hp-ord-A3-pp-N-N.wav		Hp-ord-C4-pp-N-N.wav		Hp-ord-E4-ff-N-N.wav		Hp-ord-G#3-mf-N-N.wav
Hp-ord-A4-ff-N-T20d.wav		Hp-ord-C5-ff-N-N.wav		Hp-ord-E4-mf-N-N.wav		Hp-ord-G#3-pp-N-N.wav
Hp-ord-A4-mf-N-N.wav		Hp-ord-C5-mf-N-N.wav		Hp-ord-E4-pp-N-N.wav		Hp-ord-G#4-ff-N-T16d.wav
Hp-ord-A4-pp-N-N.wav		Hp-ord-C5-pp-N-N.wav		Hp-ord-E5-ff-N-N.wav		Hp-ord-G#4-mf-N-N.wav
Hp-ord-A5-ff-N-N.wav		Hp-ord-C6-ff-N-N.wav		Hp-ord-E5-mf-N-N.wav		Hp-ord-G#4-pp-N-N.wav
Hp-ord-A5-mf-N-N.wav		Hp-ord-C6-mf-N-N.wav		Hp-ord-E5-pp-N-N.wav		Hp-ord-G#5-ff-N-N.wav
Hp-ord-A5-pp-N-N.wav		Hp-ord-C6-pp-N-N.wav		Hp-ord-E6-ff-N-N.wav		Hp-ord-G#5-mf-N-N.wav
Hp-ord-A6-ff-N-T15d.wav		Hp-ord-C7-ff-N-N.wav		Hp-ord-E6-mf-N-N.wav		Hp-ord-G#5-pp-N-N.wav
Hp-ord-A6-mf-N-N.wav		Hp-ord-C7-mf-N-N.wav		Hp-ord-E6-pp-N-N.wav		Hp-ord-G#6-ff-N-N.wav
Hp-ord-A6-pp-N-N.wav		Hp-ord-C7-pp-N-T16d.wav		Hp-ord-E7-ff-N-N.wav		Hp-ord-G#6-mf-N-N.wav
Hp-ord-B0-mf-N-N.wav		Hp-ord-D#1-ff-N-N.wav		Hp-ord-E7-mf-N-N.wav		Hp-ord-G#6-pp-N-N.wav
Hp-ord-B1-ff-N-N.wav		Hp-ord-D#1-mf-N-N.wav		Hp-ord-E7-pp-N-N.wav		Hp-ord-G1-ff-N-N.wav
Hp-ord-B1-mf-N-N.wav		Hp-ord-D#1-pp-N-N.wav		Hp-ord-F#1-ff-N-N.wav		Hp-ord-G1-mf-N-N.wav
Hp-ord-B1-pp-N-N.wav		Hp-ord-D#2-ff-N-N.wav		Hp-ord-F#1-mf-N-N.wav		Hp-ord-G1-pp-N-N.wav
Hp-ord-B2-ff-N-N.wav		Hp-ord-D#2-mf-N-N.wav		Hp-ord-F#1-pp-N-T14u.wav	Hp-ord-G2-ff-N-N.wav
Hp-ord-B2-mf-N-N.wav		Hp-ord-D#2-pp-N-N.wav		Hp-ord-F#2-ff-N-N.wav		Hp-ord-G2-mf-N-N.wav
Hp-ord-B2-pp-N-N.wav		Hp-ord-D#3-ff-N-N.wav		Hp-ord-F#2-mf-N-N.wav		Hp-ord-G2-pp-N-N.wav
Hp-ord-B3-ff-N-N.wav		Hp-ord-D#3-mf-N-N.wav		Hp-ord-F#2-pp-N-N.wav		Hp-ord-G3-ff-N-N.wav
Hp-ord-B3-mf-N-N.wav		Hp-ord-D#3-pp-N-N.wav		Hp-ord-F#3-ff-N-N.wav		Hp-ord-G3-mf-N-N.wav
Hp-ord-B3-pp-N-N.wav		Hp-ord-D#4-ff-N-N.wav		Hp-ord-F#3-mf-N-N.wav		Hp-ord-G3-pp-N-N.wav
Hp-ord-B4-ff-N-N.wav		Hp-ord-D#4-mf-N-N.wav		Hp-ord-F#3-pp-N-N.wav		Hp-ord-G4-ff-N-R100u.wav
Hp-ord-B4-mf-N-N.wav		Hp-ord-D#4-pp-N-N.wav		Hp-ord-F#4-ff-N-N.wav		Hp-ord-G4-mf-N-N.wav
Hp-ord-B4-pp-N-N.wav		Hp-ord-D#5-ff-N-N.wav		Hp-ord-F#4-mf-N-N.wav		Hp-ord-G4-pp-N-N.wav
Hp-ord-B5-ff-N-N.wav		Hp-ord-D#5-mf-N-N.wav		Hp-ord-F#4-pp-N-N.wav		Hp-ord-G5-ff-N-N.wav
Hp-ord-B5-mf-N-N.wav		Hp-ord-D#5-pp-N-N.wav		Hp-ord-F#5-ff-N-N.wav		Hp-ord-G5-mf-N-N.wav
Hp-ord-B5-pp-N-N.wav		Hp-ord-D#6-ff-N-N.wav		Hp-ord-F#5-mf-N-N.wav		Hp-ord-G5-pp-N-N.wav
Hp-ord-B6-ff-N-N.wav		Hp-ord-D#6-mf-N-N.wav		Hp-ord-F#5-pp-N-N.wav		Hp-ord-G6-ff-N-N.wav
Hp-ord-B6-mf-N-N.wav		Hp-ord-D#6-pp-N-N.wav		Hp-ord-F#6-ff-N-N.wav		Hp-ord-G6-mf-N-N.wav
Hp-ord-B6-pp-N-N.wav		Hp-ord-D#7-ff-N-N.wav		Hp-ord-F#6-mf-N-N.wav		Hp-ord-G6-pp-N-N.wav
Hp-ord-C#1-ff-N-N.wav		Hp-ord-D#7-mf-N-N.wav		Hp-ord-F#6-pp-N-N.wav		Hp-ord-G7-ff-N-T16d.wav
Hp-ord-C#1-mf-N-T10u.wav	Hp-ord-D#7-pp-N-T10d.wav	Hp-ord-F#7-ff-N-N.wav		Hp-ord-G7-mf-N-N.wav
Hp-ord-C#1-pp-N-N.wav		Hp-ord-D1-ff-N-N.wav		Hp-ord-F#7-mf-N-T10d.wav	Hp-ord-G7-pp-N-T15d.wav
Hp-ord-C#2-ff-N-N.wav		Hp-ord-D1-mf-N-T11u.wav		Hp-ord-F#7-pp-N-T10d.wav
Hp-ord-C#2-mf-N-N.wav		Hp-ord-D1-pp-N-T11u.wav		Hp-ord-F1-ff-N-N.wav
Hp-ord-C#2-pp-N-N.wav		Hp-ord-D2-ff-N-N.wav		Hp-ord-F1-mf-N-N.wav
***@***.*** ordinario %

**Comment by benhackbarth** [comment]
OK. Could you please edit the file audioguide/anallinkage.py and replace the entire function __createDescriptorsFile__ with [this](https://pastebin.com/JfXPVjYs), and then send me an email with the printout? Cheers

**Comment by steinmetzer** [comment]
***@***.*** ~ % python3 /Users/fauvel/Music/AudioGuide/agConcatenate.py /Users/fauvel/Music/AudioGuide/rs/extfoldtest.py
audioguide1.74 -> /Users/fauvel/Music/AudioGuide/audioguide
python3.9.10 -> ***@***.***/bin/python3.9
               Evaluating TARGET cage.aiff from 0.00-11.40                
100% [================================================================]
	Found 21 segments (threshold=-25.0 offsetrise=1.50 offsetthreshadd=12.00).



                           Evaluating CORPUS...                           
  0% [----------------------------------------------------------------]
	***@***.***                    /Volumes/T7/other/SoundsAndLoops/Orchidea/_OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/._Hp-ord-B0-mf-N-N.wav /Users/fauvel/Music/AudioGuide/audioguide/data /Users/fauvel/Music/AudioGuide/audioguide/data/._Hp-ord-B0-mf-N-N-f4d0d63059a0-ircamd.npy /Users/fauvel/Music/AudioGuide/audioguide/data/._Hp-ord-B0-mf-N-N-f4d0d63059a0.json /Users/fauvel/Music/AudioGuide/audioguide/ircamdescriptor-2.8.6/ircamdescriptor-2.8.6 /Users/fauvel/Music/AudioGuide/audioguide/data/ircamdescriptor.config.txt
['/Users/fauvel/Music/AudioGuide/audioguide/ircamdescriptor-2.8.6/ircamdescriptor-2.8.6', '/Volumes/T7/other/SoundsAndLoops/Orchidea/_OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/._Hp-ord-B0-mf-N-N.wav', '/Users/fauvel/Music/AudioGuide/audioguide/data/ircamdescriptor.config.txt']
output ---------------
ircamdescriptor
---------------
(c) IRCAM, 2008-2012 

Sound file I/O using libsndfile libsndfile-1.0.17patchb,
  Copyright Erik de Castro Lopo, licenced under the GNU LGPL
  (see http://www.mega-nerd.com/libsndfile or libsndfile.License)

version: 2.8.6
release: Mar 15 2013

error: cannot open the requested audio file

infodict {'ircamd_columns': {'power': 0}}
Traceback (most recent call last):
  File "/Users/fauvel/Music/AudioGuide/agConcatenate.py", line 29, in <module>
    ag.execute()
  File "/Users/fauvel/Music/AudioGuide/audioguide/__init__.py", line 59, in execute
    self.load_corpus()
  File "/Users/fauvel/Music/AudioGuide/audioguide/__init__.py", line 138, in load_corpus
    self.cps = concatenativeclasses.corpus(self.ops.CORPUS, self.ops.CORPUS_GLOBAL_ATTRIBUTES, self.ops.RESTRICT_CORPUS_SELECT_PERCENTAGE_BY_STRING, self.ops.SEARCH_PATHS, self.AnalInterface, self.p)
  File "/Users/fauvel/Music/AudioGuide/audioguide/concatenativeclasses.py", line 522, in __init__
    cpsSeg = sfsegment.corpusSegment(*corpusSegParams)
  File "/Users/fauvel/Music/AudioGuide/audioguide/sfsegment.py", line 141, in __init__
    sfsegment.__init__(self, filename, startSec, endSec, AnalInterface, envDb=envDb, envAttackSec=envAttackSec, envDecaySec=envDecaySec, envSlope=envSlope, normtag='cps')
  File "/Users/fauvel/Music/AudioGuide/audioguide/sfsegment.py", line 24, in __init__
    self.soundfileTotalDuration, self.soundfileChns = AnalInterface.validateAnalResource(self.filename)
  File "/Users/fauvel/Music/AudioGuide/audioguide/anallinkage.py", line 312, in validateAnalResource
    self.initAnalResource(sffile)
  File "/Users/fauvel/Music/AudioGuide/audioguide/anallinkage.py", line 359, in initAnalResource
    self.rawData[sffile]['info'], self.rawData[sffile]['ircamd'] = self.__createDescriptorsFile__(sffile, self.analdir, descriptorfile, infofile, self.ircamdescriptor_bin, self.config_loc)
  File "/Users/fauvel/Music/AudioGuide/audioguide/anallinkage.py", line 291, in __createDescriptorsFile__
    infodict['lengthsec'] = infodict['lengthsamples']/float(infodict['sr'])
KeyError: 'lengthsamples'
***@***.*** ~ %

**Comment by benhackbarth** [comment]
OK. I suspect that what might be happening here is that there are files in this directory that are not soundfiles. More specifically, the program is failing when analyzing "._Hp-ord-B0-mf-N-N.wav", which (apologies if you know this) will not show up in the finder browser as files that start with '.' are hidden in OSX. Is it possible that there are hidden files in this folder that were create by some other analysis program?

If this is the case, you have two options. 1) Delete these files or 2) tell audioguide to ignore them like this:
csf("/Volumes/T7/other/SoundsAndLoops/Orchidea/_OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/", wholeFile=True, excludeStr=['._'])

Please let me know if this works.

**Comment by steinmetzer** [comment]
Hm, there are no invisible files in the folder, I checked this with different means.
Also, if I copy the folder (with hypothetically invisible files) to the internal drive, the script runs smoothly.

So I guess somewhere the filename gets changed to ._filename, but this only happens when it is located on the external drive.
Weird.

Roby

**Comment by benhackbarth** [comment]
Apparently this is [a thing](https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them).

Time Machine perhaps?

try running 
dot_clean /Volumes/T7/other/SoundsAndLoops/Orchidea/OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/

I guess I need to add a clause that ignores ._ files in directories.

**Comment by benhackbarth** [comment]
`csf("/Volumes/T7/other/SoundsAndLoops/Orchidea/OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/", wholeFile=True, excludeStr=["._"])` should work though, right?

**Comment by steinmetzer** [comment]
This definitely works:
csf("/Volumes/T7/other/SoundsAndLoops/Orchidea/OrchideaSOL2020_release/rsOrchideaSOL2020/PluckedStrings/Harp/ordinario/", wholeFile=True, excludeStr=["._"])

But dot_clean did the trick! Now it works even without excludeStr.
It must have something to do with the fact that the drive is exFAT formated.
When I bought the drive, it came with this formating and I thought I would be a good thing to keep it as such, as it would allow me to use the drive on Windows too.
Seen from now, it was not such a great idea, especially that I never use Windows ;-)

What is nevertheless strange is that the files are not visible, not even in the Terminal.

Ben, how can I thank you for your help and effort?
That was an absolutely outstanding support!

Thanks,
Roby


PS:
One more thing: I have seen in the tutorials that you have individual note sound files from the Vienna library. Where did you get these from, mine are bundled in big .dat files? Did you extract them somehow?

**Comment by benhackbarth** [comment]
Glad to hear this works now. 

> Ben, how can I thank you for your help and effort?

Could you please download the latest git code? The directory search function now ignores ._files as well as has better error handling if sound files cannot be analyzed. If you could work with the new code and let me know if anything is amiss, that'd be great. Cheers, Ben
