### ISSUE TITLE
Error with simple example

### ISSUE THREAD

**Issue by zseramnay** [benhackbarth/audioguide#15]
Dear Ben,

Hope all is well with you !

Preparing for a class next monday, I run the example script to test if all is well and I have issues...
I haven't used AG for some time now and I have a new M2 machine on Ventura. May be that's related.

The security system also keeps bothering about running IrcamDesriptors.

So once past that problem, I can't get the agSegmentSf.py to work on the "lachenmann.aiff" for the "01-simplest.py" example that I want to show the students.

All the best dear Ben
Yan Maresz

Here is the error :

(base) yanmaresz@MacBook-Pro audioguide-1.75 % python3 /Users/yanmaresz/kDrive/Apps/audioguide-1.75/agSegmentSf.py /Users/yanmaresz/kDrive/Apps/audioguide-1.75/examples/lachenmann.aiff 
audioguide1.75 -> /Users/yanmaresz/kDrive/Apps/audioguide-1.75/audioguide
python3.11.4 -> /Users/yanmaresz/anaconda3/bin/python3
Traceback (most recent call last):
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.75/agSegmentSf.py", line 57, in <module>
    ag.load_target()
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.75/audioguide/__init__.py", line 84, in load_target
    self.tgt.initAnal(self.AnalInterface, self.ops, self.p)
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.75/audioguide/sfsegment.py", line 255, in initAnal
    self.whole = sfsegment(self.filename, self.startSec, self.endSec, AnalInterface, envDb=self.envDb, normtag='tgtwhole')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.75/audioguide/sfsegment.py", line 24, in __init__
    self.soundfileTotalDuration, self.soundfileChns = AnalInterface.validateAnalResource(self.filename)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.75/audioguide/anallinkage.py", line 313, in validateAnalResource
    self.initAnalResource(sffile)
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.75/audioguide/anallinkage.py", line 360, in initAnalResource
    self.rawData[sffile]['info'], self.rawData[sffile]['ircamd'] = self.__createDescriptorsFile__(sffile, self.analdir, descriptorfile, infofile, self.ircamdescriptor_bin, self.config_loc)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.75/audioguide/anallinkage.py", line 289, in __createDescriptorsFile__
    myarray = np.fromfile(os.path.join(STAGING_DIRECTORY, 'EnergyEnvelope_ShortTermFeature_space1.raw'), dtype=np.float, count=-1, sep='')
                                                                                                               ^^^^^^^^
  File "/Users/yanmaresz/anaconda3/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
(base) yanmaresz@MacBook-Pro audioguide-1.75 %

**Comment by zseramnay** [comment]
Would replacing every instance of np.float to np.float64 in the audioguide directory do the trick ?

**Comment by zseramnay** [comment]
Tried with 1.74

(base) yanmaresz@MacBook-Pro ~ % cd /Users/yanmaresz/kDrive/Apps/audioguide-1.74 
(base) yanmaresz@MacBook-Pro audioguide-1.74 % python3 /Users/yanmaresz/kDrive/Apps/audioguide-1.74/agSegmentSf.py /Users/yanmaresz/kDrive/Apps/audioguide-1.74/examples/lachenmann.aiff
audioguide1.74 -> /Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide
python3.11.4 -> /Users/yanmaresz/anaconda3/bin/python3
Traceback (most recent call last):
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/agSegmentSf.py", line 57, in <module>
    ag.load_target()
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/__init__.py", line 84, in load_target
    self.tgt.initAnal(self.AnalInterface, self.ops, self.p)
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/sfsegment.py", line 255, in initAnal
    self.whole = sfsegment(self.filename, self.startSec, self.endSec, AnalInterface, envDb=self.envDb, normtag='tgtwhole')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/sfsegment.py", line 24, in __init__
    self.soundfileTotalDuration, self.soundfileChns = AnalInterface.validateAnalResource(self.filename)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/anallinkage.py", line 306, in validateAnalResource
    self.initAnalResource(sffile)
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/anallinkage.py", line 353, in initAnalResource
    self.rawData[sffile]['info'], self.rawData[sffile]['ircamd'] = self.__createDescriptorsFile__(sffile, self.analdir, descriptorfile, infofile, self.ircamdescriptor_bin, self.config_loc)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/anallinkage.py", line 266, in __createDescriptorsFile__
    f = open(os.path.join(STAGING_DIRECTORY, 'SpectralCentroid_ShortTermFeature_space2.info.txt'))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/data/tmp/SpectralCentroid_ShortTermFeature_space2.info.txt'
(base) yanmaresz@MacBook-Pro audioguide-1.74 %

**Comment by zseramnay** [comment]
fixed by changing "np.float" to "float"  on lines 289 and 297 in anallinkage.py
this fix was not in the 1.75 ditrib

**Comment by benhackbarth** [comment]
Hi Yan, Nice to read you. You're correct in your proposed fix -- Sergio actually caught this months ago and I forgot to push his changes to the public repo. The fix is up now as current version 1.76. Best, B
