### ISSUE TITLE
reaper export pitch or rate?

### ISSUE THREAD

**Issue by robinmeier** [benhackbarth/audioguide#17]
when exporting to reaper, the transposition parameter get's translated to a reaper media item's pitch parameter. in reaper, pitch seems to be always rate-compensated, i.e. the clip doesnt change duration. however, in csound the clip changes in speed, when transposition is applied. 

i would like to have the same behaviour in reaper, i.e. changing pitch, changes speed. no rate compensation.

is it possible to do this?
i haven't found the option neither in reaper nor in audioguide.

**Comment by benhackbarth** [comment]
Hi Robin,

Your post is correct. When adding reaper support the only way I could find to do transposition was rate-compensated. You can find the reaper docs I used to write the output method here: https://github.com/ReaTeam/Doc/blob/master/State%20Chunk%20Definitions. If you're able to spy something I missed I am happy to try to add it into audioguide.

B

**Comment by robinmeier** [comment]
hey! yeah, check line 279 in that document. if i understand correctly, i think you change the rate (first field), rather than the pitch (third field) and set the second field to 0. then it should change playrate without compensating pitch. you would just need to convert the transposition value from midicents to a rate ratio.

**Comment by benhackbarth** [comment]
Working on it...

**Comment by benhackbarth** [comment]
Can you try the latest code to see if this works now?

There is now a option RPP_TRANS_AFFECTS_SPEED which is True by default. This tells Reaper to use speed-style transposition. If False, it reverts to using Reapers time preservation magic.

**Comment by robinmeier** [comment]
totally works. amazing!!! 
thanks so much ben <3
this is super helpful!!!

**Comment by benhackbarth** [comment]
:)
