### ISSUE TITLE
reaper re-rendered when -i

### ISSUE THREAD

**Issue by robinmeier** [benhackbarth/audioguide#18]
run agConcatenate in interactive -i mode and generate a reaper file
comment out the reaper file, change some settings and save
-> new reaper file with the new settings but the old filename gets created, thus overwriting the previous rpp file

**Comment by benhackbarth** [comment]
confirmed bug. looking into it now.

**Comment by benhackbarth** [comment]
should be all fixed in latest
https://github.com/benhackbarth/audioguide/releases/tag/1.78
