### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by robinmeier** [benhackbarth/audioguide#2]
hello ben, is there a version of audioguide that runs on linux? cheers, robin

**Comment by benhackbarth** [comment]
hi robin ! unfortunately, no, audioguide is osx only at the moment due to external binary dependancies.

**Comment by robinmeier** [comment]
thanks ben. which binaries exactly?

**Comment by benhackbarth** [comment]
Descriptor analysis in audioguide/audioguide/ircamdescriptor-2.8.6 and the dylib wrappers for sndfile in the same directory.
