### ISSUE TITLE
batch agSegmentSf issue

### ISSUE THREAD

**Issue by zseramnay** [benhackbarth/audioguide#3]
Hello,

I have this problem when using "python agSegmentSf.py mydir/*.wav" to segment a bunch of audio files at once.

The problem is that the numpy (ircamd.npy) resulting file (in audioguide-1.72/audioguide/data) is getting bigger as the directory contents are being analyzed.

As a test, if I redo a agSegmentSf.py on the one audio file that created the largest numpy file, I get a normal, small sized file. This is very problematic as very big database segmentation analysis is going to create files that are bigger than what they 'can' be.

Thanks for taking a look into this Ben

All the very best
Yan Maresz

Attached is an example of a file that creates an 11MB .npy file when created in a batch manner and the same file segmented alone (2MB)
[exemple.zip](https://github.com/benhackbarth/audioguide/files/6796518/exemple.zip)

**Comment by benhackbarth** [comment]
Thanks Yan - I found the issue and hopefully fixed it. Can you try downloading the current repo and see if it works on your side?  Cheers, Ben

**Comment by zseramnay** [comment]
Hello Ben
Thanks ! yes, it's looking good now.
All the best
Yan
