### ISSUE TITLE
can't segment some audio files

### ISSUE THREAD

**Issue by zseramnay** [benhackbarth/audioguide#6]
Ben
There is something going on with some audio files.
Other than an extremely low amplitude I don't see anything...

Here is the error and one sound file to repro.
Best

Yan

(base) yan-MBP-Retina:audioguide-1.74 yanmaresz$ python agSegmentSf.py /Users/yanmaresz/kDrive/Samples/pPianos/ConTimbrePiano/piano-ordinario_without_pedal/*.wav
audioguide1.74 -> /Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide
python3.9.7 -> /Users/yanmaresz/opt/anaconda3/bin/python
Traceback (most recent call last):
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/agSegmentSf.py", line 57, in <module>
    ag.load_target()
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/__init__.py", line 84, in load_target
    self.tgt.initAnal(self.AnalInterface, self.ops, self.p)
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/sfsegment.py", line 255, in initAnal
    self.whole = sfsegment(self.filename, self.startSec, self.endSec, AnalInterface, envDb=self.envDb, normtag='tgtwhole')
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/sfsegment.py", line 22, in __init__
    self.rmsAmplitudeFromFilename, self.dynamicFromFilename = descriptordata.getDynamicFromFilename(self.printName, AnalInterface.dynToDbDict, AnalInterface.stringToDynDict, notFound=-1000)
  File "/Users/yanmaresz/kDrive/Apps/audioguide-1.74/audioguide/descriptordata.py", line 641, in getDynamicFromFilename
    return dynToDbDict[dynamic], dynamic
KeyError: 'piano
[piano-ordinario_without_pedal-A#0-ppp-1.wav.zip](https://github.com/benhackbarth/audioguide/files/7875336/piano-ordinario_without_pedal-A.0-ppp-1.wav.zip)
'

**Comment by benhackbarth** [comment]
Are you sure that it isn't trying to segment a zip file in the folder, piano-ordinario_without_pedal-A#0-ppp-1.wav.zip? Otherwise please send me the folder on wetransfer and I'll take a look for you.

**Comment by zseramnay** [comment]
Ben, no need. 
Try to segment the audio file attached above in the zip, you will reproduce the issue even with that one file.
no zip off any sort in the folder.

Best
Yan

**Comment by benhackbarth** [comment]
Thanks for catching this Yan. This is fixed now in git. Could you download the latest and let me know if this is fixed?

FYI, I'm not sure you need to segment audiofiles like this. If each file contains one note, I would just leave them unsegmented and use csf(wholeFile=True)

**Comment by zseramnay** [comment]
Thank you Ben !
I was not actualy segmenting this file but when using wholeFile=True, the analysis stage lead to the same error.
Now I'll be able to work with piano suond that have note and dynmic infos.

Best
Y

**Comment by benhackbarth** [comment]
Confirmed that this is fixed now.
